// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecVopono(arg1, arg2) {
  return window['go']['main']['App']['ExecVopono'](arg1, arg2);
}

export function GetWireguardConfigs() {
  return window['go']['main']['App']['GetWireguardConfigs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportWireguardConfig() {
  return window['go']['main']['App']['ImportWireguardConfig']();
}

export function RestartSingbox() {
  return window['go']['main']['App']['RestartSingbox']();
}

export function WriteSingboxConfig(arg1) {
  return window['go']['main']['App']['WriteSingboxConfig'](arg1);
}
