// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Deploy(arg1) {
  return window['go']['main']['App']['Deploy'](arg1);
}

export function EmitLog(arg1, arg2) {
  return window['go']['main']['App']['EmitLog'](arg1, arg2);
}

export function GetBackendStatus() {
  return window['go']['main']['App']['GetBackendStatus']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function ImportProxyConfigs() {
  return window['go']['main']['App']['ImportProxyConfigs']();
}

export function KillVopono(arg1) {
  return window['go']['main']['App']['KillVopono'](arg1);
}

export function LaunchStrict(arg1, arg2) {
  return window['go']['main']['App']['LaunchStrict'](arg1, arg2);
}

export function ListDesktopApps() {
  return window['go']['main']['App']['ListDesktopApps']();
}

export function ListVoponoProcesses() {
  return window['go']['main']['App']['ListVoponoProcesses']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function MeasureLatency(arg1) {
  return window['go']['main']['App']['MeasureLatency'](arg1);
}

export function RestartSingbox() {
  return window['go']['main']['App']['RestartSingbox']();
}

export function SaveState(arg1) {
  return window['go']['main']['App']['SaveState'](arg1);
}

export function StopSingbox() {
  return window['go']['main']['App']['StopSingbox']();
}

export function Undeploy() {
  return window['go']['main']['App']['Undeploy']();
}

export function WriteSingboxConfig(arg1) {
  return window['go']['main']['App']['WriteSingboxConfig'](arg1);
}
