// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecVopono(arg1:string,arg2:string):Promise<main.VoponoProcess>;

export function GetServiceStatus():Promise<main.ServiceStatus>;

export function Greet(arg1:string):Promise<string>;

export function ImportWireguardConfig():Promise<main.ImportedProxy>;

export function KillVopono(arg1:string):Promise<void>;

export function ListDesktopApps():Promise<Array<main.DesktopApp>>;

export function ListVoponoProcesses():Promise<Array<main.VoponoProcess>>;

export function LoadState():Promise<main.AppState>;

export function RestartSingbox():Promise<void>;

export function SaveState(arg1:main.AppState):Promise<void>;

export function StopSingbox():Promise<void>;

export function WriteSingboxConfig(arg1:string):Promise<void>;
