// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecVopono(arg1:string,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportWireguardConfig():Promise<any>;

export function RestartSingbox():Promise<void>;

export function WriteSingboxConfig(arg1:string):Promise<void>;
